<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

<br>

**4. Create a tensor "x" from the array above**

<br>

**5. Change the dtype of x from `int32` to `int64`**

<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

<br>

**7. Return the right-hand column of tensor `x`**

<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

<br>

**10. Find the matrix product of `x` and `y`.**

</div>

# Laboratory Task 5

# 1. Standard Imports

In [4]:
import numpy as np
import torch
import random

# 2. Set Seed Function

In [5]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

# 3. Numpy Array

In [6]:
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("arr:", arr)
print("dtype:", arr.dtype)

arr: [3 4 2 4 4 1]
dtype: int32


# 4. Tensor x From Array

In [7]:
x = torch.from_numpy(arr)
print("x:", x)
print("dtype:", x.dtype)
print("shape:", x.shape)

x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
dtype: torch.int32
shape: torch.Size([6])


# 5. int32 to int64

In [8]:
x = x.to(torch.int64)
print("x:", x)
print("dtype:", x.dtype)

x: tensor([3, 4, 2, 4, 4, 1])
dtype: torch.int64


# 6. Reshaping

In [9]:
# Option A — .reshape()
x = x.reshape(3, 2)

print("x:\n", x)
print("shape:", x.shape)

x:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
shape: torch.Size([3, 2])


# 7. Right Hand Column of x

In [11]:
right_col = x[:, -1]   
print("right column:", right_col)

right column: tensor([4, 4, 1])


# 8. Square Values

In [12]:
# Option A — torch.square()
x_squared = torch.square(x)

print("x squared:\n", x_squared)
print("x unchanged:\n", x)

x squared:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
x unchanged:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


# 9. Create Tensor y Matrix-Multipliable with x

In [ ]:
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print("y:\n", y)
print("shape:", y.shape)

# 10. Matrix Product

In [ ]:
result = x @ y          # or torch.matmul(x, y) or torch.mm(x, y)
print("x @ y:\n", result)
print("shape:", result.shape)